### ISSUE TITLE
 IndexError: list index out of range

### ISSUE THREAD

**Issue by varshavk98** [oyyarko/opencv_arko#1]
while running the .ipynb file OpenColab I'm getting " IndexError: list index out of range" error when open the video file.How can I avoid that
---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

<ipython-input-4-0bb1ebfc7a2c> in <module>()
----> 1 videofile = get_video()
      2 
      3 with open(video_file_test, 'wb') as f:
      4   f.write(videofile)

<ipython-input-3-2c798d37cca5> in get_video()
    114   display(HTML(VIDEO_HTML))
    115   data = eval_js("data")
--> 116   binary = b64decode(data.split(',')[1])
    117 
    118   return binary

**Comment by oyyarko** [comment]
It's because the webcam isn't recording at all. I would suggest you to use google chrome, Firefox has some issue with opening webcam.

**Comment by varshavk98** [comment]
Okay,thank you
